"""Add status, admin_note, response_note, uploaded_at to cx_request

Revision ID: 054da8c80352
Revises: 1b8fa0c16b24
Create Date: 2025-07-09 08:55:52.861475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054da8c80352'
down_revision = '1b8fa0c16b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cx_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('admin_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('response_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cx_request', schema=None) as batch_op:
        batch_op.drop_column('response_note')
        batch_op.drop_column('admin_note')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
