"""Add uploaded_at to CxRequest

Revision ID: 1b8fa0c16b24
Revises: 4a96c60cd806
Create Date: 2025-07-09 08:25:55.662280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8fa0c16b24'
down_revision = '4a96c60cd806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cx_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cx_request', schema=None) as batch_op:
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###
