"""Add internet_status to Cx

Revision ID: 22367d6cd736
Revises: 6f508aa3ea10
Create Date: 2025-07-23 09:55:56.583374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22367d6cd736'
down_revision = '6f508aa3ea10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cx', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internet_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cx', schema=None) as batch_op:
        batch_op.drop_column('internet_status')

    # ### end Alembic commands ###
