"""Make email unique in ReactivationRequest

Revision ID: 2adad9a649f1
Revises: 7860773c7f3a
Create Date: 2025-07-18 08:24:48.911775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adad9a649f1'
down_revision = '7860773c7f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactivation_request', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reactivation_email', ['email'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactivation_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
