"""Add fields to Notification model

Revision ID: 6f30099dc4b7
Revises: c82536574e06
Create Date: 2025-07-10 10:22:38.049714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f30099dc4b7'
down_revision = 'c82536574e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notif_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('reference_id')
        batch_op.drop_column('amount')
        batch_op.drop_column('status')
        batch_op.drop_column('notif_type')

    # ### end Alembic commands ###
