"""Add billing_from and billing_to to SOA

Revision ID: 7498fbb0b8cc
Revises: 6f30099dc4b7
Create Date: 2025-07-10 11:52:32.355417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7498fbb0b8cc'
down_revision = '6f30099dc4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('billing_to', sa.Date(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soa', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('billing_to')
        batch_op.drop_column('billing_from')

    # ### end Alembic commands ###
