"""Update Ticket Type

Revision ID: d7c63a0a9e56
Revises: 83773aa6f5b9
Create Date: 2025-07-21 11:58:33.677533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c63a0a9e56'
down_revision = '83773aa6f5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('form_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('ticket_type')

    # ### end Alembic commands ###
