"""Add extension_name to Cx model

Revision ID: f0a3d1248728
Revises: f4e1635dd9b0
Create Date: 2025-07-04 16:02:29.795005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a3d1248728'
down_revision = 'f4e1635dd9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cx', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cx', schema=None) as batch_op:
        batch_op.drop_column('extension_name')

    # ### end Alembic commands ###
