"""Added middle_initial column

Revision ID: f4e1635dd9b0
Revises: 3e66984d78ba
Create Date: 2025-07-04 15:39:59.579906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e1635dd9b0'
down_revision = '3e66984d78ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cx', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_initial', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cx', schema=None) as batch_op:
        batch_op.drop_column('middle_initial')

    # ### end Alembic commands ###
